const fs = require('fs')
const path = require('path')

console.log('Generating COMPARISON_TABLE.md...')

/**
 * Setup data for generating table
 */
const COLUMNS = [
  'Library',
  'Stars',
  'Size',
  'Last Commit',
  'Plugins'
]

const BADGEN = {
  Stars: 'https://badgen.net/github/stars/{githubRelative}',
  Size: 'https://badgen.net/packagephobia/publish/{libraryName}',
  'Last Commit': 'https://badgen.net/github/last-commit/{githubRelative}'
}

// Add more libraries here
const LIBRARIES = [
  {
    Library: 'remarkable',
    githubRelative: 'jonschlinkert/remarkable',
    Plugins: ':heavy_check_mark:'
  },
  {
    Library: 'react-remark',
    githubRelative: 'remarkjs/react-remark',
    Plugins: ':heavy_check_mark:'
  }
]

/**
 * Generate table rows and columns
 */
const rows = []
LIBRARIES.forEach((library) => {
  const columns = []
  COLUMNS.forEach((column, i) => {
    if (library[column]) {
      columns.push(library[column])
    } else if (BADGEN[column]) {
      const template = BADGEN[column]
      const badgenUrl = template
        .replace('{githubRelative}', library.githubRelative)
        .replace('{libraryName}', library.Library)
      const field = `![${library.Library} ${column}](${badgenUrl})`
      columns.push(field)
    } else {
      columns.push('N/A')
    }
  })
  rows.push(columns.join(' | '))
})

/**
 * Text blocks
 */
const WARNING_HEADER =
`# IMPORTANT\n
This file is generated by the \`yarn generate-comparison-table\` command. 
If you would like to add more libraries, add them to the 
\`generateComparisonTable.js\` script.\n`

const TABLE_HEADER =
`${COLUMNS.join('|')}
${COLUMNS.map(_ => '-').join('|')}`

/**
 * Combine all elements and output to COMPARISON_TABLE file
 */
const output =
`${WARNING_HEADER}
${TABLE_HEADER}
${rows.join('\n')}`

const filePath = path.join(__dirname, '../../docs/COMPARISON_TABLE.md')

fs.writeFileSync(filePath, output)

console.log('Finished generating COMPARISON_TABLE.md')
